// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sehtie.Data;

#nullable disable

namespace Sehtie.Repository.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240315124447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sehtie.Data.Entities.Booking", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("No");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Bookings", (string)null);

                    b.HasData(
                        new
                        {
                            No = 1,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "do1",
                            PatientId = "pat1"
                        },
                        new
                        {
                            No = 2,
                            Date = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "do1",
                            PatientId = "pat1"
                        },
                        new
                        {
                            No = 3,
                            Date = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "do1",
                            PatientId = "pat1"
                        });
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "do1",
                            Category = "ophthalmologist",
                            DisplayName = "do1Ahmed",
                            Email = "do1Ahmed@gmail.com",
                            IsDeleted = false,
                            PersonalNumber = "N129841239",
                            PhoneNumber = "963931243567"
                        },
                        new
                        {
                            Id = "do2",
                            Category = "cardiologist",
                            DisplayName = "do2Abdulrahman",
                            Email = "do2Abdulrahman@gmail.com",
                            IsDeleted = false,
                            PersonalNumber = "N129841238",
                            PhoneNumber = "963923678945"
                        });
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "pat1",
                            DisplayName = "pat1Ahmed",
                            Email = "do1Ahmed@gmail.com",
                            IsDeleted = false,
                            PersonalNumber = "N129841249",
                            PhoneNumber = "963931245567"
                        },
                        new
                        {
                            Id = "pat2",
                            DisplayName = "pat2Abdulrahman",
                            Email = "pat2Abdulrahman@gmail.com",
                            IsDeleted = false,
                            PersonalNumber = "N129841248",
                            PhoneNumber = "963953678945"
                        });
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ActiveIngredient")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AppliesTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "rec01",
                            ActiveIngredient = false,
                            AppliesTo = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfIssue = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "do1",
                            PatientId = "pat1"
                        });
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Report", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("No");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reports", (string)null);

                    b.HasData(
                        new
                        {
                            No = 1,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "something in her eyes",
                            DoctorId = "do1",
                            PatientId = "pat1"
                        });
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Booking", b =>
                {
                    b.HasOne("Sehtie.Data.Entities.Doctor", "Doctor")
                        .WithMany("Bookings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sehtie.Data.Entities.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Recipe", b =>
                {
                    b.HasOne("Sehtie.Data.Entities.Doctor", "Doctor")
                        .WithMany("Recipes")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sehtie.Data.Entities.Patient", "Patient")
                        .WithMany("Recipes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Report", b =>
                {
                    b.HasOne("Sehtie.Data.Entities.Doctor", "Doctor")
                        .WithMany("Reports")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sehtie.Data.Entities.Patient", "Patient")
                        .WithMany("Reports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Doctor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Recipes");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Sehtie.Data.Entities.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Recipes");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
